# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcNLLCondAgeAtLength_cpp <- function(nLenCl, MaxAge, ObsCatchFreqAtLengthAndAge, ExpCatchPropLengthGivenAge, ExpCatchPropAtAge) {
    .Call(`_L3Assess_CalcNLLCondAgeAtLength_cpp`, nLenCl, MaxAge, ObsCatchFreqAtLengthAndAge, ExpCatchPropLengthGivenAge, ExpCatchPropAtAge)
}

CalcCatches_AgeAndLengthBasedCatchCurves_cpp <- function(params, NatMort, RecLenDist, InitRecNumber, MaxAge, nLenCl, midpt, RetAtLength, SelAtLength, DiscMort, LTM) {
    .Call(`_L3Assess_CalcCatches_AgeAndLengthBasedCatchCurves_cpp`, params, NatMort, RecLenDist, InitRecNumber, MaxAge, nLenCl, midpt, RetAtLength, SelAtLength, DiscMort, LTM)
}

CalcLTM_cpp <- function(TimeStepGrowthSizeInc, CVSizeAtAge, lbnd, midpt, ubnd, nLenCl) {
    .Call(`_L3Assess_CalcLTM_cpp`, TimeStepGrowthSizeInc, CVSizeAtAge, lbnd, midpt, ubnd, nLenCl)
}

UpdateGrowthAndSurvival_cpp <- function(ReprodPattern, TimeStep, nTimeSteps, nLenCl, InitRatioFem, RecLenDist, NatMort, FemZAtLen, MalZAtLen, PropFemAtLen, LTM_Fem, LTM_Mal, FemWtAtLen, MalWtAtLen, ReprodScale, FemPropMatAtLen, MalPropMatAtLen) {
    .Call(`_L3Assess_UpdateGrowthAndSurvival_cpp`, ReprodPattern, TimeStep, nTimeSteps, nLenCl, InitRatioFem, RecLenDist, NatMort, FemZAtLen, MalZAtLen, PropFemAtLen, LTM_Fem, LTM_Mal, FemWtAtLen, MalWtAtLen, ReprodScale, FemPropMatAtLen, MalPropMatAtLen)
}

